version: 3.9


machine-learning-client:
      build: ./machine-learning-client
      dockerfile: ./Dockerfile
      ports: 
        - "5001:5001"
      depends_on:
      - mongodb



web-app:
    build: ./web-app
    dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - machine-learning-client
    environment: